'\" t
.\"     Title: __zzip_fetch_disk_trailer
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 0.13.62
.\"    Manual: zziplib Function List
.\"    Source: zziplib
.\"  Language: English
.\"
.TH "__ZZIP_FETCH_DISK_TR" "3" "0\&.13\&.62" "zziplib" "zziplib Function List"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
__zzip_fetch_disk_trailer \- \&.\&.\&.
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <zzip/lib\&.h>
.fi
.ft
.HP \w'int\ __zzip_fetch_disk_trailer('u
.BI "int __zzip_fetch_disk_trailer((int\ fd,\ zzip_off_t\ filesize,\ struct\ _disk_trailer\ *_zzip_restrict\ trailer,\ zzip_plugin_io_t\ io));"
.SH "DESCRIPTION"
.PP
(missing description)
.SH "AUTHOR"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Guido Draheim <guidod@gmx\&.de> Tomi Ollila <too@iki\&.fi>
.RE
.SH "COPYRIGHT"
.PP
Copyright (c) 1999,2000,2001,2002,2003 Guido Draheim All rights reserved, use under the restrictions of the Lesser GNU General Public License or alternatively the restrictions of the Mozilla Public License 1\&.1
