'\" t
.\"     Title: zzip_init_io
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 0.13.62
.\"    Manual: zziplib Function List
.\"    Source: zziplib
.\"  Language: English
.\"
.TH "ZZIP_INIT_IO" "3" "0\&.13\&.62" "zziplib" "zziplib Function List"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zzip_init_io, zzip_get_default_io \- \&.\&.\&.
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <zzip/lib\&.h>
.fi
.ft
.HP \w'int\ zzip_init_io('u
.BI "int zzip_init_io((zzip_plugin_io_handlers_t\ io,\ int\ flags));"
.HP \w'zzip_plugin_io_t\ zzip_get_default_io('u
.BI "zzip_plugin_io_t zzip_get_default_io((void));"
.SH "DESCRIPTION"
.PP
The
\fBzzip_get_default_io\fR
function returns a zzip_plugin_io_t handle to static defaults wrapping the posix io file functions for actual file access\&. The returned structure is shared by all threads in the system\&.
.SH "AUTHOR"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Guido Draheim <guidod@gmx\&.de> Mike Nordell <tamlin\-@\-algonet\-se>
.RE
.SH "COPYRIGHT"
.PP
Copyright (c) 2002,2003 Guido Draheim All rights reserved, use under the restrictions of the Lesser GNU General Public License or alternatively the restrictions of the Mozilla Public License 1\&.1
