#!/bin/bash
# Copyright 2002-2003 by Kai 'Oswald' Seidler, oswald@apachefriends.org, GPL-licensed

if test "x$XAMPP_ROOT" = "x"
then
	echo "Dont call this script directly!"
	exit 1
fi

. $XAMPP_ROOT/share/xampp/xampplib

echo "XAMPP: " $($GETTEXT "Quick security check...")

$XAMPP_ROOT/share/xampp/checkmysqlport
$XAMPP_ROOT/share/xampp/checkpmamysqluser
$XAMPP_ROOT/share/xampp/checkmysql
$XAMPP_ROOT/share/xampp/checkftppassword

echo "XAMPP: " $($GETTEXT "Done.")
